{{- if .Values.openhabcloudApp.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ohcloud.fullname" . }}
  labels:
    {{- include "ohcloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.openhabcloudApp.service.type }}
  ports:
    - port: {{ .Values.openhabcloudApp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ohcloud.selectorLabels" . | nindent 4 }}
{{- end }}