apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ohcloud.fullname" . }}-config-json-template
  labels:
    {{- include "ohcloud.labels" . | nindent 4 }}
data:
  config.json.template: |-
    {
    "system": {
      "host": "${DOMAIN_NAME}",
      "proxyHost": "${PROXY_DOMAIN_NAME}",
      "port": "443",
      "protocol": "https",
      "logger" : {
        "type": "console"
      },
      "healthEndpoint": {
        "enabled": ${ENABLE_HEALTH_ENDPOINT}
      },
      "subDomainCookies": {{ .Values.openhabcloudApp.features.subdomainCookies }}
    },
    "express":{
      "key" : "${EXPRESS_KEY}"
    },
    "apn" : {
      "gateway": "gateway.push.apple.com",
      "cert": "certs/aps/aps_production_cert.pem",
      "key": "certs/aps/aps_production_key.pem",
      "passphrase": "${APN_PASSPHRASE}"
    },
    "gcm" : {
      "senderId": "${GCM_SENDER_ID}",
      "serviceFile" : "${GCM_SERVICE_FILE}"
    },
    "ifttt" : {
      "iftttChannelKey" : "key",
      "iftttTestToken" : "token"
    },
    "mongodb": {
        "hosts": ["${MONGODB_URI}"],
        "db": "${MONGODB_DB}",
        "user": "${MONGODB_USER}",
        "password": "${MONGODB_PASS}"
    },
    "redis": {
        "host": "${REDIS_HOST}",
        "port": "6379",
        "password": "${REDIS_PASSWORD}"
    },
    "mailer": {
        "host" : "${MAIL_HOST}",
        "port": 465,
        "secureConnection": true,
        "user": "${MAIL_USER}",
        "password": "${MAIL_PASSWORD}",
        "from": "${MAIL_FROM}"
    },
    "legal": {
        "terms" : "",
        "policy": ""
    },
    "registration_enabled": false
    }