apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ohcloud.fullname" . }}-config-json
  labels:
    {{- include "ohcloud.labels" . | nindent 4 }}
data:
  config.json: |-
    {
    "system": {
      "host": "{{ .Values.openhabcloudApp.features.domainName }}",
      "proxyHost": "{{ .Values.openhabcloudApp.features.proxyDomainName }}",
      "port": "443",
      "protocol": "https",
      "logger" : {
        "type": "console"
      },
      "healthEndpoint": {
        "enabled": {{ .Values.openhabcloudApp.features.enableHealthEndpoint }}
      },
      "subDomainCookies": {{ .Values.openhabcloudApp.features.subdomainCookies }}
    },
    "express":{
      "key" : "{{- include "getValueFromSecret" (dict "Namespace" .Release.Namespace "Name" "ohcloud-config" "Length" 10 "Key" "EXPRESS_KEY")  -}}"
    },
    "apn" : {
      "gateway": "gateway.push.apple.com",
      "cert": "certs/aps/aps_production_cert.pem",
      "key": "certs/aps/aps_production_key.pem",
      "passphrase": "{{- include "getValueFromSecret" (dict "Namespace" .Release.Namespace "Name" "ohcloud-config" "Length" 10 "Key" "APN_PASSPHRASE")  -}}"
    },
    {{- if .Values.openhabcloudApp.features.enableGcm -}}
    "gcm" : {
      "senderId": "{{- include "getValueFromSecret" (dict "Namespace" .Release.Namespace "Name" "ohcloud-config" "Length" 10 "Key" "GCM_SENDER_ID")  -}}",
      "serviceFile" : "{{- include "getValueFromSecret" (dict "Namespace" .Release.Namespace "Name" "ohcloud-config" "Length" 10 "Key" "GCM_SERVICE_FILE")  -}}"
    },
    {{- end }}
    "ifttt" : {
      "iftttChannelKey" : "key",
      "iftttTestToken" : "token"
    },
    "mongodb": {
        "hosts": ["{{ .Values.openhabcloudApp.features.mongodbUri }}"],
        "db": "{{ .Values.openhabcloudApp.features.mongodbDb }}",
        "user": "{{- include "getValueFromSecret" (dict "Namespace" .Release.Namespace "Name" "ohcloud-config" "Length" 10 "Key" "MONGODB_USER")  -}}",
        "password": "{{- include "getValueFromSecret" (dict "Namespace" .Release.Namespace "Name" "ohcloud-config" "Length" 10 "Key" "MONGODB_PASS")  -}}"
    },
    "redis": {
        "host": "{{ .Values.openhabcloudApp.features.redisHost }}",
        "port": "6379",
        "password": "{{- include "getValueFromSecret" (dict "Namespace" .Release.Namespace "Name" "ohcloud-config" "Length" 10 "Key" "REDIS_PASSWORD")  -}}"
    },
    "mailer": {
        "host" : "{{ .Values.openhabcloudApp.features.mailHost }}",
        "port": 465,
        "secureConnection": true,
        "user": "{{- include "getValueFromSecret" (dict "Namespace" .Release.Namespace "Name" "ohcloud-config" "Length" 10 "Key" "MAIL_USER")  -}}",
        "password": "{{- include "getValueFromSecret" (dict "Namespace" .Release.Namespace "Name" "ohcloud-config" "Length" 10 "Key" "MAIL_PASSWORD")  -}}",
        "from": "{{ .Values.openhabcloudApp.features.mailFrom }}"
    },
    "legal": {
        "terms" : "",
        "policy": ""
    },
    "registration_enabled": {{ .Values.openhabcloudApp.features.registrationEnabled }}
    }