{{- if .Values.openhabcloudApp.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ohcloud.serviceAccountName" . }}
  labels:
    {{- include "ohcloud.labels" . | nindent 4 }}
  {{- with .Values.openhabcloudApp.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.openhabcloudApp.serviceAccount.automount }}
{{- end }}
