{{- if or (and (not .Values.existingSecret) .Values.adminPassword) (and .Values.smtp.enabled .Values.smtp.password (not .Values.smtp.existingSecret)) (gt (len .Values.extraSecretEnv) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud.fullname" . }}-secrets
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and (not .Values.existingSecret) .Values.adminPassword }}
  {{ .Values.existingSecretKey }}: {{ .Values.adminPassword | quote }}
  {{- end }}
  {{- if and .Values.smtp.enabled .Values.smtp.password (not .Values.smtp.existingSecret) }}
  smtp-password: {{ .Values.smtp.password | quote }}
  {{- end }}
  {{- range $key, $value := .Values.extraSecretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
