{{- if and (not .Values.postgresql.existingSecret) (not .Values.postgresql.password) }}
{{- fail "Set postgresql.existingSecret or postgresql.password" }}
{{- end }}
{{- if not .Values.postgresql.host }}
{{- fail "postgresql.host is required" }}
{{- end }}
{{- if and (not .Values.postgresql.existingSecret) .Values.postgresql.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spliit.postgresSecretName" . }}
  labels:
    {{- include "spliit.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.postgresql.existingSecretUsernameKey }}: {{ .Values.postgresql.username | quote }}
  {{ .Values.postgresql.existingSecretPasswordKey }}: {{ .Values.postgresql.password | quote }}
{{- end }}
